# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Laplace density function using Rcpp
#' @description Laplace density function using Rcpp
#' @param x the sample points
#' @return the value of density function in x
#' @examples
#' \dontrun{
#' dlap <- dlapC(5)
#' dlap
#' }
#' @export
dlapC <- function(x) {
    .Call('_StatComp20084_dlapC', PACKAGE = 'StatComp20084', x)
}

#' @title A Random Walk sampler using Rcpp
#' @description A Random Walk sampler using Rcpp
#' @param N the length of chains
#' @param sigma the variance of normal distribution
#' @return the generated chain
#' @examples
#' \dontrun{
#' rwlap <- rwlapC(5000, 2)
#' plot(1:5000, rwlap$x, ylab = "x", 
#' main = expression(paste(sigma, '= 2')), type = "l")
#' }
#' @export
rwlapC <- function(N, sigma) {
    .Call('_StatComp20084_rwlapC', PACKAGE = 'StatComp20084', N, sigma)
}

